version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    volumes:
      - frontend_dist:/app/dist

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    environment:
      - PORT=8080
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8080:8080"
    volumes:
      - frontend_dist:/root/dist
    networks:
      - portfolio-network
    restart: unless-stopped
    depends_on:
      - frontend

volumes:
  frontend_dist:

networks:
  portfolio-network:
    driver: bridge